### ISSUE TITLE
how to send sticker randomly

### ISSUE THREAD

**Issue by andreutomo** [line/line-bot-sdk-php#115]
guys i want to ask how to send sticker line randomly when user send sticker.
thx

**Comment by lintangtimur** [comment]
**rand(0,430)** will generate random number for stickerId

**Comment by tm-tech** [comment]
- Define a function like below.

```
function replyStickerMessage($bot,$replyToken,$packageId,$stickerId) {
    $response = $bot->replyMessage($replyToken,new \LINE\LINEBot\MessageBuilder\StickerMessageBuilder($packageId,$stickerId));
    if (!$response->isSucceeded()) {
        error_log('replyStickerMessage :' . $response->getHTTPStatus() . ' ' . $response->getRawBody())
    }
}
```



- Use it like below if you want to send a random sticker.
Then, it is necessary to define the range of package id because it is not a continuous.
Please refer to [https://developers.line.me/media/messaging-api/sticker_list.pdf](url)  about the sticker list.

`replyStickerMessage($bot,$event->getReplyToken(),1,rand(1,10) ;`



- You can also define some stickers that you send randamly in advance.

```
$packageid = array(2,5,6,9) ;
replyStickerMessage($bot,$event->getReplyToken(),1,$packageid[rand(0,count($packageid)-1)]) ;
```


enjoy...
