### ISSUE TITLE
How can we identify users across different providers?

### ISSUE THREAD

**Issue by thosieucoi** [line/line-bot-sdk-php#248]
Dear everyone,

We've developing a web application using LINE login v2.1 with multiples providers.

We try to get user profiles by API https://api.line.me/v2/profile but for each provider, same user will have different userId.
In documents LINE mentioned "The user ID is unique only to an individual provider. The same LINE user will have a different user ID for different providers. Avoid using the user ID to identify users across different providers."

How can we identify users across different providers?

**Comment by tkgauri** [comment]
Hello @thosieucoi,

Due to security reasons it is not possible to do so.
Moreover this question is related to LINE Login api and not LINE Messaging sdk; hence should you have further questions related to LINE Login api, we would recommend you to submit the question on our [community website](https://www.line-community.me/questions) instead of creating issue on this repo.

Thank you!

**Comment by thosieucoi** [comment]
@tkgauri thank you so much for your response. I understand my case.
