### ISSUE TITLE
Use [] instead of array_merge

### ISSUE THREAD

**Issue by Vaduz** [line/line-bot-sdk-php#346]
Calling `array_merge` is so slow, so we want to use `[]` operator instead.
See: https://stackoverflow.com/questions/23348339/optimizing-array-merge-operation

**Comment by tokuhirom** [comment]
`array_merge` in the hand written code was already removed.

Some `array_merge` are comming from openapi-generator.
https://github.com/OpenAPITools/openapi-generator/blob/3278eea9a4d644c48ea41318c30f18ad15d91288/modules/openapi-generator/src/main/resources/php/HeaderSelector.mustache#L129
But it's not a critical issue. Since the network overhead is greater than calling `array_merge`. We can close this ticket.
