### ISSUE TITLE
[Input] Set default value for parameter

### ISSUE THREAD

**Issue by vortexgin** [line/line-bot-sdk-php#59]
Dear Admin, 

I have a suggestion to set default value for parameter on TextMessageBuilder

``
class TextMessageBuilder implements MessageBuilder 
{ 
... 
public function __construct($text, array $extraTexts = array()) 
... 
} 
``

i think $extraTexts is an optional parameter, and it made error when someone forget to set value for it.

**Comment by moznion** [comment]
First of all, there is no problem even if you forget to append `$extraTexts` because that is a variadic function via `...` (see: http://php.net/manual/en/migration56.new-features.php). That is ensured by [this test](https://github.com/line/line-bot-sdk-php/blob/e16d9ca/tests/LINEBot/SendTextTest.php#L92); this test case doesn't raise error.

And your suggestion has a problem that threatens backward compatibility. `A variadic function` and `a function that has an array default value` are different. In other words, your change breaks the signature of function. So we cannot accept your suggestion.

FYI: #58 changes related topic.
