### ISSUE TITLE
How to send more than one reply?  part 2

### ISSUE THREAD

**Issue by sandmanzz** [line/line-bot-sdk-php#68]
I see previous issue about this, but its already closed. I try implement but its not work
![image](https://cloud.githubusercontent.com/assets/21254367/24330574/1a04835e-124b-11e7-9a95-7e992cb73e86.png)

and i got

![image](https://cloud.githubusercontent.com/assets/21254367/24330579/3b9a895a-124b-11e7-95bb-54688ea57bac.png)

**Comment by Naufal-FR** [comment]
@sandmanzz Are you using full blown API or the tiny version of it ? 
It seems you're trying to use the full version but with the tiny version codes which is different.

**Comment by sandmanzz** [comment]
hmmm, what you mean by full blown and tiny ? maybe we have different perception.

**Comment by Naufal-FR** [comment]
@sandmanzz If you import the `LineBotTiny.php` from [this](https://github.com/line/line-bot-sdk-php/tree/master/line-bot-sdk-tiny) to your project, then you're using the tiny version of this API.

If you use composer as stated in README then that means you're using the full version of the API

**Comment by sandmanzz** [comment]
@Naufal-FR  i use from [http://uzulla.hateblo.jp/entry/2016/10/07/164740](url) , it seems combine bot tiny and full

**Comment by Naufal-FR** [comment]
@sandmanzz Well, it's kinda out off topic if you outside codes but i'll assume it's the full version by the looks of it. 

As stated in the error log you need to create a `MessageBuilder` object first that holds your messages and then passing it into the `replyMessage` function. 

This codes below will create an object holding two message,
```$myMessages = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('First', 'Second');```

You'll then pass the variable name (which is `$myMessages`) into the `replyMessage` function, 
```$bot->replyMessage('<reply token>', $myMessages);```

Your original codes uses the tiny version structure which is not needed because the full version has `TextMessageBuilder` classes to create you messages.

**Comment by sandmanzz** [comment]
owh i see.. okay.. 
thanksfull
but can we send different object ?
ex text and image

**Comment by Naufal-FR** [comment]
@sandmanzz You can by changing `TextMessageBuilder` into other classes depending on your need. For example if you want an image use `ImageMessageBuilder` instead of `TextMessageBuilder`. Although you need to note that different classes requires different parameter to works. You can see the full list of classes [here](https://github.com/line/line-bot-sdk-php/tree/master/src/LINEBot/MessageBuilder) and the examples from the [API documentation](https://devdocs.line.me/en/).

**Comment by sandmanzz** [comment]
thanks you save my day
