### ISSUE TITLE
return bool or something if it is only support on smartphone

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#80]
hello, i want to ask about the response if the message only support on our Smartphone 

`$msg = new TemplateMessageBuilder ("Oops!", $carousel);`

i would to making a template message, but since the template only can be used on smartphone and the bot will return `"Opps! <line break> Please check it on your smartphone"` if it is not supported

simply i need to add another response on my bot, so even it is not supported. I can show the response manually without template.

what kind of `$msg` response is ? so i can be able to different the template and the not supported response

or it is possible to do it?

**Comment by moznion** [comment]
In short there is no way to check whether target device(s) supports the template message or not. Because messages are often sent to multiple devices so it cannot to handle each individual device.

Alternatively, `altText` may help you to treat devices that doesn't support template messages (ref: https://devdocs.line.me/en/#template-messages). Contents of `altText` will be appear when the client doesn't support the message type.
